### ISSUE TITLE
Chopy scrolling

### ISSUE THREAD

**Issue by judebert** [stevepryde/dstructio#1]
Set up a server, played on a local browser; scrolling was pretty choppy.

**Comment by stevepryde** [comment]
Can you please provide more information?

1. Try playing http://dstruct.io directly. Did you find that one equally "choppy" using the same browser on the same client machine?
2. Which OS was the server running on? Is the hardware sufficient to run the server at 30fps (i.e. not maxing out CPU or memory)?
3. Which client OS and browser? I noticed during testing that Microsoft Edge sometimes performed poorly. Of other browsers, only Chrome (& chromium) uses WebGL - all others use HTML5 canvas. This seemed to provide the best performance for each one.
4. What was the bandwidth like between client and server? If either cannot keep up sending data back and forth every frame, that will affect your frame rate.
5. Try a different browser if you can and see if that makes a difference.

Ideally it'd be great to find out what FPS both server and client were running at, which would require some logging or similar. There are some lines commented in client.js relating to displaying FPS on screen. For the server you'd need to just log the FPS once per second or something.

Thanks.

**Comment by judebert** [comment]
Sorry for the brevity of the original post.  Happy to help out, and I'm not implying any criticism with this request.

1. http://dstruct.io on the same machine (but different network) was also pretty choppy.  
2. OSX 10.11.6 3.1GHz i7 16GB DDR3 -- it runs another 2D top-down game, Endless Sky, with nice smooth scrolling, but that's in a dedicated window, not a browser.  Narwhale.io and Shooting Heads scroll smoothly.  
3. Client runs on the same machine, under Chrome 56.0.2924.87 64-bit.  Firefox 50.1.0 behaves similarly. 
4. The client and server were running on the same machine; if bandwidth is the issue, we really need to work on reducing the payload.
5. Firefox was the same or slower. 

I found and uncommented the FPS display lines in client.js, and updated the server.js from 900s between logs to 60s between logs.  There was no noticeable difference, and I can't find any server logs beyond the terminal printout.

**Comment by stevepryde** [comment]
Thanks for the extra info.

If you see the same from dstruct.io then that rules out your server setup. I just had a look at Narwhale.io and ironically I found the scrolling on that one (looking at the movement of the gridlines, not the narwhal) to be more choppy than dstruct.io (although still barely noticeable and easily playable). Perhaps I'm not seeing what you're seeing, though.

It doesn't look like your client machine, OS, browser, or network should be an issue, although I don't have access to a mac and did not test this on one.

Perhaps what you're seeing is due to the way dstruct.io does FPS limiting. It simply skips frames in order to limit the game to 30fps effective (to match the server), while the client actually runs at 60fps (and perhaps that is only limited by vsync, not sure). I did wonder about adding interpolation between updates rather than skipping frames on the client, but that would add a lot of complexity I think.

I also see plenty of tearing artifacts on Chrome too (on Linux). I'm using phaser.io and was under the impression that vsync is enabled by default, so I'm not sure what's going on there.

It's difficult to determine whether the choppiness you're talking about is an actual difference between what you're seeing and what I'm seeing, or whether it is merely a difference in personal tolerance.

**Comment by judebert** [comment]
Not seeing any tearing artifacts, myself.  I did get a nice smooth scroll by examining the example at https://github.com/photonstorm/phaser-examples/blob/master/examples/camera/smooth%20follow.js and setting the camera follow in client.js to FOLLOW_LOCKON.
